#pragma once

#include "pch.hpp"

/* Lua Notes:
 * Free variables are placed in the _ENV table. The default value for _ENV is _G, the global "environment",
 *   making free variables - by default - global variables. lua_getglobal accesses this _G "environment".
 * lauxlib is LAuxLib
 * Errors generated by Lua will always be strings, but users can return any type of value as an error.
 *   This has to be handled by the host program.
 */

namespace lua {
    using CFunction = std::function<int(lua_State *)>;
}
